RDKB-32005 RDKB-27531: [Dunfell] ccsp-dmcli undefined reference to discoverComp
Reason for change: Compilation error undefined reference to discoverComp.
Test Procedure: Check if recipe builds fine.
Risks: Low.
Signed-off-by: SaliniVikraman_Rajeswari@comcast.com

(cherry picked from commit 1f7ba78faba77f9ddd3378ba664e1efec37b2d7a)
Change-Id: I2a584024a32148aedd12525ff6a781257e79c053